# Kamil Sienkiewicz <sienkiewiczkm@gmail.com>
# ------------------------------------------------------------------------------

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# ------------------------------------------------------------------------------
# Fonts

cask "font-atkinson-hyperlegible"

# Monospace fonts
cask "font-fantasque-sans-mono-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# ------------------------------------------------------------------------------
# CLI tools

brew "bitwarden-cli"
brew "cmake"
brew "curl"
brew "exa"                  # ls improved; https://github.com/ogham/exa
brew "ffmpeg"               # video tools
brew "fzf"                  # fuzzy search
brew "gh"                   # GitHub cli
brew "git"
brew "gnupg"                # GPG
brew "hopenpgp-tools"       # GPG tools: hkt, hokey, hop, hot
brew "htop"
brew "httpie"
brew "hyperfine"            # benchmarking
brew "imagemagick"          # image utilities: magick, convert, identify, mogrify etc.
brew "insect"               # scientific calculator
brew "llvm"                 # clang
brew "lnav"                 # log navigator
brew "mermaid-cli"          # chart generator
brew "moreutils"            # chronic, vipe and others
brew "neovim"
brew "p7zip"                # 7z
brew "paperkey"             # saving keys in text format for backups
brew "par2"                 # PAR 2.0 generation and verification tool
brew "qrencode"             # QR code generator
brew "rename"               # rename in CLI with regex
brew "speedtest-cli"        # https://www.speedtest.net/apps/cli
brew "svgo"                 # optimization tool for SVGs
brew "temurin"              # OpenJDK (Java Development Kit) binaries, https://adoptium.net/
brew "the_silver_searcher"  # ag, https://github.com/ggreer/the_silver_searcher
brew "tldr"                 # concise man pages based on examples
brew "tmux"                 # terminal multiplexer
brew "watch"                # watch tool to repeat command
brew "watson"               # time measurements
brew "wget"
brew "ykman"                # Yubikey management
brew "youtube-dl"           # youtube downloader
brew "zsh"

# ------------------------------------------------------------------------------
# Apps

cask "anki"
cask "balenaetcher"         # etching ISOs on USB sticks
cask "blender"
cask "calibre"              # ebook management
cask "coconutbattery"
cask "discord"
cask "disk-inventory-x"
cask "firefox"
cask "flux"
cask "folx"                 # file/torrent downloader
cask "foobar2000"
cask "ghidra"
cask "gimp"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "itsycal"
cask "kap"                  # gif screen recorder
cask "keepassxc"
cask "keka"
cask "kitty"
cask "licecap"              # screen recording (gifs)
cask "meld"                 # diff tool supporting 3-way merge
cask "steam"
cask "visual-studio-code"
cask "vlc"
cask "vox"                  # winamp-like audio player
cask "skitch"               # screenshot annotation tool

# ------------------------------------------------------------------------------
# Archived stuff - sometimes may be useful
# cask "db-browser-for-sqlite"